#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := gpio
IDF_PATH = /mnt/d/Sourcetree/ESP8266/ESP8266_RTOS_SDK-3.1
include $(IDF_PATH)/make/project.mk

